### ISSUE TITLE
[✨ feature] Docs

### ISSUE THREAD

**Issue by Fredkiss3** [zane-ops/zane-ops#311]
## Content

- [x] v1 annoucement page :
        - with a summary of all the features available 

### Getting started docs 
-  [x] more screenshots
-  [x] update the installation docs 
 - [x] system requirements
- [x] How to Deploy and setup a fresh instance of ZaneOps : 
        - ~~[Cloud init](https://github.com/zane-ops/cloud-init) : precise that it should replace the `/root` with their default user and also replace the default url to use for ROOT domains and zaneops dashboard~~ 
        - DNS setup for deploying : for services and deployments if possible, recommend using wildcard if possible 
        - Using the IP
        - Using cloudflare tunnel
- [x] How to deploy apps using github actions, recommend using our action : https://github.com/zane-ops/auto-deploy-action, but also show using just `curl`

### More details 
- [x] log collection (every 5s) and retention policy : 2 weeks (cleaned up every day at midnight)
- [x] metrics collection and retention policy : 30 days, ran every 5 seconds, cleaned up every day at midnight
- [x] Zero downtime deployments and situations triggering it
- [x] automatic system cleanup (every 4h)

### tutorials
- [x] How to deploy an app to zaneops : 
       - https://github.com/zane-ops/guestbook
       - ~~Demo video~~
       - Link to production
       
### Tasks
- [x] Simple cdn app for downloading the makefile ? 
       - like coolify, and it will allow us to get some basic analytics by making a simple API that tracks downloads ~~using umami : https://umami.is/docs/api~~, we used a simple cloudflare worker with a D1 database
- [x]  update  https://github.com/zane-ops/cloud-init
- [x]  update  https://github.com/zane-ops/auto-deploy-action
- [x]  tag v1.0 : images and github release

 
## Additional context

- Should add precisions that for each service they will add to zaneops, it also needs to be added to the DNS 
  - If they want to automatically have all their apps on a subdomain to their server, they could use wildcard `*` domains on CF with proxy_status=true & http enabled on zaneops (with  `make deploy-with-http`), CF will handle the SSL certs for them instead of caddy installed on zaneops
  - should also precise that changing from http to https or vice-versa requires stopping the stack and restarting it for caddy to take into account the new policy
- ZaneOps architecture will be done much later

---
- [x] Are you willing to make a PR for this ?

**Comment by Fredkiss3** [comment]
done
